defaults:
  - common
  - agent: hsd3
  - _self_


hydra:
  run:
    dir: ./outputs/${hydra.job.name}.${robot}.${goal_space}.${subsets}.${now:%Y-%m-%d-%H-%M-%S}/


max_steps: 15e6
robot: Franka
goal_space: fpos_fposd_fvel_feuler_fswitwi_fposboxz
subsets: from_lo
action_interval: 5
eps: 1.0
auto_adapt: true

eval:
  interval: 15e4
  metrics:
    is_success: final:default
    box_goal_pos_dist: final:default
    box_goal_rot_dist: final:default
    episode_energy: final:default
  video:  null # for box push dense, eval video crashes iff env.eval_procs > 1 i.e. env.eval_args.fork == true. TODO: debug

video: 
  interval: 15e4
visdom:
  offline: true

env:
  name: BiskBoxPushingTemporalSparse-v0
  train_procs: 1
  eval_procs: 50
  args:
    robot: ${robot}
  wrappers:
    - time
    - bisk_features: ${agent.goal_space.key}:${goal_space}

agent:
  trace: true
  action_interval: ${action_interval}
  goal_space:
    robot: ${robot}
    features: ${goal_space}
    key: _goal_space
    subsets: ${subsets}
    from_lo_eps: ${eps}
  lo:
    init_from: checkpoint-lo.pt

model:
  hi:
    pi_task: pi_d2rl_discrete_d_256
    pi_subgoal: pi_d2rl_mt_d_256
    q: qd_d2rl_flattsg_d_256
  lo:
    pi: pi_d2rl_d_1024

optim:
  hi:
    pi_task:
      _target_: torch.optim.Adam
      lr: 3e-4
      fuse: true
    pi_subgoal:
      _target_: torch.optim.Adam
      lr: 3e-4
      fuse: true
    q:
      _target_: torch.optim.Adam
      lr: 1e-4
      fuse: true
